config/routes.rb
YashProject::Application.routes.draw do
  #resources :pictures

  #resources :albums

#get request than url name than controller name and # and method name than , than as than name which is used in view	
  get "questions/index"

  get "profiles/show"
  #get "/pages/:page" => "pages#show"
  get "pages/about"
  
  #devise_for :users

 # devise_scope :user do
#	get 'register' , to: 'devise/registrations#new',as: :register
#	get 'login' , to: 'devise/sessions#new',as: :login
#	get 'logout' , to: 'devise/sessions#destroy',as: :logout	
#  end
  
  as :user do
	get '/register' , to: 'devise/registrations#new',as: :register
	get '/login' , to: 'devise/sessions#new',as: :login
	get '/logout' , to: 'devise/sessions#destroy',as: :logout	
  end
 
 devise_for :users,skip: [:sessions]
 
 as :user do 		
	get "/login" => 'devise/sessions#new', as: :new_user_session
	post "/login" => 'devise/sessions#create', as: :user_session
	delete "logout" => 'devise/sessions#destroy', as: :destroy_user_session
 end
 
  resources :questions, except: [:new] do
		resources :answers, only: [:create]	
  end
  
  resources :user_friendships do
	member do
		put :accept
		put :block
	end
  end
  
  scope ":profile_name" do
    resources :albums do
      resources :pictures
    end
  end
  
  resources :statuses  
		get 'feed', to: 'statuses#index', as: :feed
		#root to: 'statuses#index'
		root to: 'questions#index'
		#get "user_profile", to: 'profiles#show'
		#match "profile" => "users#show", :as => 'profile'
		get "statuses/p_show/:id" => "statuses#p_show", :as => 'p_show'

		get '/your_questions', to: 'questions#your_questions'
		#get '/status_page', to: 'statuses#status_page'
		#get 'profiles/show/:id', to: 'profiles#show'
		get '/:id', to: 'profiles#show',as: 'profile'
		#get '/search', to: 'questions#search'
		# post 'search' , to: 'questions#search',as: :search
		#map.resources :search, :collection => { :index => :get, :results => :get }
		#root :to => "home#index"
		
 end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  
  def show
	@user = User.find_by_profile_name(params[:id])	
		if @user
			#@statuses = Status.all
			@statuses = @user.statuses.all
			render action: :show
		else	
		render file 'public/404', status: 404, formats: [:html]
		end
  end	
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/show.html.erb
<div class="page-header">
  <h1><% if current_user.avatar? %>
    <div class="control-group">
      <label class="control-label">Current Profile Image</label>
      <div class="controls">
        <%= image_tag @user.avatar.url(:thumb) %>   <%= @user.full_name %>
      </div>
    </div>
       
    <% end %> </h1>
</div>

<% if signed_in? %>
<div id="friend-status">
  <% if current_user.friends.include?(@user) || current_user.pending_friends.include?(@user) %>
    <%= link_to "Edit Friendship", edit_user_friendship_path(friend_id: @user), class: 'btn' %>
  <% else %>
    <%= link_to "Add Friend", new_user_friendship_path(friend_id: @user), class: 'btn', id: 'add-friendship', data: { friend_id: @user.to_param }%>
  <% end %>
</div>
<% end %>


<% if @statuses %>
  <% @statuses.each do |status| %>
    <div class="well">
      <%= status.content %>
      <hr />
      <%= link_to time_ago_in_words(status.created_at), status_path(status) %> ago
    </div>
  <% end %>
<% end %>