config/routes.rb
YashProject::Application.routes.draw do
  #resources :pictures

  #resources :albums

#get request than url name than controller name and # and method name than , than as than name which is used in view	
  get "questions/index"

  get "profiles/show"
  #get "/pages/:page" => "pages#show"
  get "pages/about"
  
  #devise_for :users

 # devise_scope :user do
#	get 'register' , to: 'devise/registrations#new',as: :register
#	get 'login' , to: 'devise/sessions#new',as: :login
#	get 'logout' , to: 'devise/sessions#destroy',as: :logout	
#  end
  
  as :user do
	get '/register' , to: 'devise/registrations#new',as: :register
	get '/login' , to: 'devise/sessions#new',as: :login
	get '/logout' , to: 'devise/sessions#destroy',as: :logout	
  end
 
 devise_for :users,skip: [:sessions]
 
 as :user do 		
	get "/login" => 'devise/sessions#new', as: :new_user_session
	post "/login" => 'devise/sessions#create', as: :user_session
	delete "logout" => 'devise/sessions#destroy', as: :destroy_user_session
 end
 
  resources :questions, except: [:new] do
		resources :answers, only: [:create]	
  end
  
  resources :user_friendships do
	member do
		put :accept
		put :block
	end
  end
  
  scope ":profile_name" do
    resources :albums do
      resources :pictures
    end
  end
  
  resources :statuses  
		get 'feed', to: 'statuses#index', as: :feed
		#root to: 'statuses#index'
		root to: 'questions#index'
		#get "user_profile", to: 'profiles#show'
		#match "profile" => "users#show", :as => 'profile'
		get "statuses/p_show/:id" => "statuses#p_show", :as => 'p_show'

		get '/your_questions', to: 'questions#your_questions'
		#get '/status_page', to: 'statuses#status_page'
		#get 'profiles/show/:id', to: 'profiles#show'
		get '/:id', to: 'profiles#show',as: 'profile'
		#get '/search', to: 'questions#search'
		# post 'search' , to: 'questions#search',as: :search
		#map.resources :search, :collection => { :index => :get, :results => :get }
		#root :to => "home#index"
		
 end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  # GET /statuses
  # GET /statuses.json
  
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update,:destroy]
  
  def index
  #yash project
    #@statuses = Status.all
	@statuses = Status.page(params[:page]).order('created_at DESC')
	#@statuses = Status.order('created_at desc').all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @statuses }
    end
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
    @status = Status.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/new
  # GET /statuses/new.json
  def new
    @status = Status.new
	@status.build_document
	 
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/1/edit
  def edit
    @status = Status.find(params[:id])	
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(params[:status])

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render json: @status, status: :created, location: @status }
      else
        format.html { render action: "new" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /statuses/1
  # PUT /statuses/1.json
  def update
    #@status = Status.find(params[:id])
	@status = current_user.statuses.find(params[:id])
	 @document = @status.document
	if params[:status] && params[:status].has_key?(:user_id)		
		params[:status].delete(:user_id) 
	end
    respond_to do |format|
      if @status.update_attributes(params[:status])&&
         @document && @document.update_attributes(params[:status][:document_attributes])
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status = Status.find(params[:id])
	#print @status
    @status.destroy

    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
	  format.js   { render :layout => false }
    end
  end
  
  def p_show
	@user = User.find(params[:id])	
	# @status = Status.find(params[:id])
		if @user
			#@statuses = Status.all
			@statuses = @user.statuses.all
			render action: :p_show
		else			 
			render file 'public/404', status: 404, formats: [:html]
		end
  end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.erb
<%= simple_form_for(@status, html: {class: "form-horizontal", multipart: true}) do |f| %>

  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


					<% f.input :user_id, collection: User.all, label_method: :full_name %>
					<% f.input_field  :content , :input_html => {:maxlength => 15, :size => 10}%>
					<% f.input_field :content, as: :text, class: "my-custom-class", rows: 5 %>
<%= f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id } %>					
<%= f.input :content, input_html:{rows:3,class:'input-xxlarge'}%>
  
 <%= f.fields_for :document do |document_fields| %>
    <% if document_fields.object.attachment? %>
    <div class="control-group">
      <label class="control-label">Current attachment</label>
      <div class="controls">
        <%= link_to document_fields.object.attachment_file_name, document_fields.object.attachment.url %>
      </div>
    </div>
    <%= document_fields.input :remove_attachment, as: :boolean, label: "Remove attachment?" %>
    <% end %>
    <%= document_fields.input :attachment, as: :file %>
  <% end %>

  
  <div style=" margin: 10px 10px 10px 0px; padding: 0px;">
  <% image_tag 'document_edit.png',width: '35px' %>
    <%= f.button :submit, class: "btn btn-success" , data: { disable_with: "Loading..." } %>
  </div>
<% end %>
 <%= link_to "Back to Statuses", statuses_path, class:'btn btn-info btn-xs'%>

app/views/statuses/_old_index.html.erb
<h1> Statuses</h1>

<table>
  

<% @statuses.each do |status| %>
  <tr>
    <td><%= status.name %></td>
    <td><%= status.content %></td>
    <td><%= link_to 'Show', status %></td>
    <td><%= link_to 'Edit', edit_status_path(status) %></td>
    <td><% link_to 'Delete', status, confirm: 'Are you sure?', method: :destroy %></td>
	<td><%= link_to 'Destroy', status, method: :delete, data:  {confirm: 'Are you sure?'} %></td>
	 <td><% link_to 'Destroy1',  { action: :destroy, id: status.id }, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	 
	<td><%= button_to "delete", status, :method => "delete" , data:  {confirm: 'Are you sure?'}%></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Status', new_status_path %>

app/views/statuses/destroy.js.erb
$('.row').bind('ajax:success', function() {
   $(this).closest('div').fadeOut();
});

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show Status', @status, class:'btn btn-info btn-xs' %> 
<% link_to 'Back', statuses_path , class:'btn btn-info btn-xs' %>

app/views/statuses/index.html.erb
<div class="page-header">
	<h2> Posts</h2>
</div>
<table>
<div style="float:right;"><%= link_to 'Post a New Status', new_status_path , class: "btn btn-success" %></div>
<% @statuses.each do |status| %>
  <% if can_display_status?(status) %>
		<div class="status">		
				<div class="row">
						<div class="span1">
						  <%= avatar_profile_link status.user, {}, class: 'pull-left' %>
							<% image_tag status.user.gravatar_url %>
							<% link_to image_tag(status.user.gravatar_url),profile_path(status.user)%>
							
						</div>
						<div class="span11">
							<strong> <% status.user.full_name %><%= link_to status.user.full_name ,profile_path(status.user)%> </strong>
							<% link_to "View Profile", {:controller => "statuses", :action => "p_show", :id => status.user_id }%>
							<% link_to status.user.full_name ,profile_path(current_user)%>
							
							<p><%= status.content %></p>
							 <%= status_document_link(status) %>
							  <div class="meta">
								Posted on
								<%= link_to time_ago_in_words(status.created_at)+ " ago", status %> 
								<% if (user_signed_in? && (current_user.id == status.user_id)) %>
								<span class="admin">
								&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
								&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
								&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
									<%= link_to "Edit" , edit_status_path(status) , class: "btn btn-success" %> &nbsp;
									<%= link_to "Delete" ,status, method: :delete , data:  {confirm: 'DELETE STATUS?'},:remote => true, :class => 'row' ,class: "btn btn-success" %> 
								</span>
								<% end %>
							</div>	
						</div>
					</div>
				</div>			
		</div>
	<% end %>	
<% end %>
</table>

<div class="digg_pagination">
	<!-- <div class="page_info">
	  <% page_entries_info @statuses %>
	</div> -->
<%= will_paginate @statuses , :previous_label => 'PREVIOUS', :next_label => 'NEXT'%>

app/views/statuses/index_old.html.erb
<div class="page-header">
	<h2> Posts</h2>
</div>
<table>
  <%= link_to 'Post a New Status', new_status_path , class: "btn btn-success" %>
<% @statuses.each do |status| %>
	<div class="status">
	
		<div class="row">
				<div class="span1">
					<% image_tag status.user.gravatar_url %>
					<%= link_to image_tag(status.user.gravatar_url, :alt => "User"),profile_path(status.user)%>
					
				</div>
				<div class="span7">
					<strong> <%= status.user.full_name %> </strong>
					<%= link_to "View Profile", {:controller => "statuses", :action => "p_show", :id => status.user_id }%>
					<%= link_to status.user.full_name , {:controller => "profiles", :action => "show", :id => status.user.profile_name }%>
					
					<p><%= status.content %></p>
					<div  style=" font-family: Raleway,Helvetica,"Helvetica Neue",Helvetica,Arial,sans-serif;"%>
						<%= link_to time_ago_in_words(status.created_at)+ " ago", status %> 
						<% if (user_signed_in? && (current_user.id == status.user_id)) %>
						<span class="admin">
						|	<%= link_to "Edit" , edit_status_path(status) %> |
							<%= link_to "Delete" ,status, method: :delete , data:  {confirm: 'DELETE STATUS?'},:remote => true, :class => 'row'%> 
						</span>
						<% end %>
				</div>
			</div>
		</div>
		
	</div>
<% end %>
<div class="digg_pagination">
	<!-- <div class="page_info">
	  <% page_entries_info @statuses %>
	</div> -->
<%= will_paginate @statuses %>

app/views/statuses/new.html.erb
<h3>Post a New status <%=  current_user.full_name %></h3>

<%= render 'form' %>

<% link_to 'Back', statuses_path %>

app/views/statuses/p_show.html.erb
<div class="page-header">
	<h1> <%= @user.full_name %> </h1>
</div>


<% if @statuses %>
	
	<% @statuses.each do |status| %>
		<div class="well">
		<%= status.content %>
		<hr/>
		<%= link_to time_ago_in_words(status.created_at), status_path(status) %> ago
		</div>
	<% end %>

<% end %>

app/views/statuses/profile_show.html.erb
<div class="page-header">
	<h1> <%= @user.full_name %> </h1>
</div>


<% if @statuses %>
	
	<% @statuses.each do |status| %>
		<div class="well">
		<%= status.content %>
		<hr/>
		<%= link_to time_ago_in_words(status.created_at), status_path(status) %> ago
		</div>
	<% end %>

<% end %>

app/views/statuses/show.html.erb
<p id="notice"><% notice %></p>

<p>
  <b><!-- Name: --></b>
  <% @status.user.full_name %>
</p>

<p>
  <b><!-- Content: --></b>
  <% @status.content %>
</p>


<% link_to 'Edit', edit_status_path(@status) %> 
<% link_to 'Back', statuses_path %>


<div class="row">
  <div class="span8 offset2">
    
      <h1>
       
        <%= @status.user.full_name %>
        
      </h1>
    

    <p>
      <%= @status.content %>
    </p>
<small><%= time_ago_in_words(@status.created_at) + " ago" %></small>
    <hr />

    <% if @status.document && @status.document.attachment? %>
      <%= status_document_link @status %>
      <hr />
    <% end %>

    <div class="meta">
      <%= link_to 'Back to Statuses', statuses_path , class:'btn btn-info btn-xs'%>
      <% if signed_in? && @status.user == current_user %>
        |
        <%= link_to "Edit Status", edit_status_path(@status), class:'btn btn-info btn-xs' %> | 
        <%= link_to "Delete", @status, method: :delete, data: { confirm: "Are you sure your want to delete this status?"} , class:'btn btn-info btn-xs'%>
      <% end %>
    </div>
  </div>
</div>