config/routes.rb
YashProject::Application.routes.draw do
  #resources :pictures

  #resources :albums

#get request than url name than controller name and # and method name than , than as than name which is used in view	
  get "questions/index"

  get "profiles/show"
  #get "/pages/:page" => "pages#show"
  get "pages/about"
  
  #devise_for :users

 # devise_scope :user do
#	get 'register' , to: 'devise/registrations#new',as: :register
#	get 'login' , to: 'devise/sessions#new',as: :login
#	get 'logout' , to: 'devise/sessions#destroy',as: :logout	
#  end
  
  as :user do
	get '/register' , to: 'devise/registrations#new',as: :register
	get '/login' , to: 'devise/sessions#new',as: :login
	get '/logout' , to: 'devise/sessions#destroy',as: :logout	
  end
 
 devise_for :users,skip: [:sessions]
 
 as :user do 		
	get "/login" => 'devise/sessions#new', as: :new_user_session
	post "/login" => 'devise/sessions#create', as: :user_session
	delete "logout" => 'devise/sessions#destroy', as: :destroy_user_session
 end
 
  resources :questions, except: [:new] do
		resources :answers, only: [:create]	
  end
  
  resources :user_friendships do
	member do
		put :accept
		put :block
	end
  end
  
  scope ":profile_name" do
    resources :albums do
      resources :pictures
    end
  end
  
  resources :statuses  
		get 'feed', to: 'statuses#index', as: :feed
		#root to: 'statuses#index'
		root to: 'questions#index'
		#get "user_profile", to: 'profiles#show'
		#match "profile" => "users#show", :as => 'profile'
		get "statuses/p_show/:id" => "statuses#p_show", :as => 'p_show'

		get '/your_questions', to: 'questions#your_questions'
		#get '/status_page', to: 'statuses#status_page'
		#get 'profiles/show/:id', to: 'profiles#show'
		get '/:id', to: 'profiles#show',as: 'profile'
		#get '/search', to: 'questions#search'
		# post 'search' , to: 'questions#search',as: :search
		#map.resources :search, :collection => { :index => :get, :results => :get }
		#root :to => "home#index"
		
 end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :album
  belongs_to :user
  attr_accessible :caption, :description, :asset

  has_attached_file :asset, styles: {
    large: "800x800>", medium: "300x200>", small: "260x180>", thumb: "80x80#"
  }
do_not_validate_attachment_file_type :asset
  def to_s
    caption? ? caption : "Picture"
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_filter :find_user
  before_filter :find_album
  before_filter :find_picture, only: [:edit, :update, :show, :destroy]
  before_filter :ensure_proper_user, only: [:edit, :new, :create, :update, :destroy]
  before_filter :add_breadcrumbs

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = @album.pictures.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pictures }
    end
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
    add_breadcrumb @picture, album_picture_path(@album, @picture)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @picture }
    end
  end

  # GET /pictures/new
  # GET /pictures/new.json
  def new
    @picture = @album.pictures.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @picture }
    end
  end

  # GET /pictures/1/edit
  def edit
    
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = @album.pictures.new(params[:picture])
    
    respond_to do |format|
      if @picture.save
       # current_user.create_activity @picture, 'created'
        format.html { redirect_to album_pictures_path(@album), notice: 'Picture was successfully created.' }
        format.json { render json: @picture, status: :created, location: @picture }
      else
        format.html { render action: "new" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pictures/1
  # PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update_attributes(params[:picture])
       # current_user.create_activity @picture, 'updated'
        format.html { redirect_to album_pictures_path(@album), notice: 'Picture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy

    respond_to do |format|
      #current_user.create_activity @picture, 'deleted'
      format.html { redirect_to album_pictures_url(@album) }
      format.json { head :no_content }
    end
  end

  def url_options
    { profile_name: params[:profile_name] }.merge(super)
  end

  private
  def ensure_proper_user
    if current_user != @user
      flash[:error] = "You don't have permission to do that."
      redirect_to album_pictures_path
    end
  end

  def add_breadcrumbs
    add_breadcrumb @user.first_name, profile_path(@user)
    add_breadcrumb "Albums", albums_path
    add_breadcrumb "Pictures", album_pictures_path(@album)
  end

  def find_user
    @user = User.find_by_profile_name(params[:profile_name])
  end

  def find_album
    if signed_in? && current_user.profile_name == params[:profile_name]
      @album = current_user.albums.find(params[:album_id])
    else
      @album = @user.albums.find(params[:album_id])
    end
  end

  def find_picture
    @picture = @album.pictures.find(params[:id])
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def can_edit_picture?(picture)
    signed_in? && current_user == picture.user
  end
end

app/views/pictures/_form.html.erb
<%= simple_form_for([@album, @picture], html: { class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :asset, as: :file %>
    <%= bootstrap_paperclip_picture f, :asset %>
    <%= f.input :caption, input_html: { class: 'input-xxlarge' } %>
    <%= f.input :description, input_html: { class: 'input-xxlarge', rows: 4 } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing picture</h1>

<%= render 'form' %>

<%= link_to 'Show', album_picture_path(@album, @picture) %> |
<%= link_to 'Back', album_pictures_path(@album) %>

app/views/pictures/index.html.erb
  <% if signed_in? && current_user == @user %>
    <%= link_to 'Add Picture', new_album_picture_path(current_user, @album), class: 'btn pull-right' %>
  <% end %>
  <h1><%= @album.title %></h1>


<ul class="thumbnails">
<% @pictures.each do |picture| %>
  <li>
    <div class="thumbnail">
    <%= link_to image_tag(picture.asset.url(:small)), album_picture_path(@user, @album, picture) %><br />
      <div class="caption">
        <% if picture.caption? %><%= picture.caption %><br /><% end %>
        
        <%= link_to 'View full size', album_picture_path(@user, @album, picture) %>

        <% if can_edit_picture?(picture) %>
          | <%= link_to "Edit", edit_album_picture_path(@album, picture) %>
          | <%= link_to "Delete", album_picture_path(@album, picture), method: :delete, data: { confirm: "Are you sure?" } %>
        <% end %>

      </div>
    </div>
  </li>  
<% end %>
</ul>

app/views/pictures/new.html.erb
<h1>New picture</h1>

<%= render 'form' %>

<%= link_to 'Back', album_pictures_path(@album) %>

app/views/pictures/show.html.erb
  <h1>Viewing Picture</h1>


<%= image_tag(@picture.asset.url(:large), alt: @picture.caption, class: 'img-polaroid') %>

<br />

<h3><%= @picture.caption %></h3>

<p><%= @picture.description %></p>

<%= link_to 'Edit', edit_album_picture_path(@album, @picture) %> |
<%= link_to 'Album', album_pictures_path(@album) %>